spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
          format_sql: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/job_db}
    username: ${JDBC_DATABASE_USERNAME:pyurtaev_job_bot_app}
    password: ${JDBC_DATABASE_PASSWORD:1pyurtaev_Job_Bot!}
bot:
  token: ${BOT_TOKEN}